{
  imports = [
    ./utils.nix
    ./legacy
    ./options.nix
    ./autocommands.nix
    ./csvview.nix
    ./lsp.nix
    ./lsp-progress.nix
    ./gitsigns.nix
    ./remember.nix
    ./undotree.nix
    ./vscode.nix
    ./codecompanion.nix
    ./repeat.nix
    ./typst-preview.nix
    ./fzf-lua.nix
    ./autopairs.nix
    ./autotag.nix
    ./treesitter-queries.nix
    ./rainbow-delimiters.nix
  ];
}
